# Generated by Django 3.2.18 on 2023-03-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20230321_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_team',
            name='badge',
            field=models.CharField(choices=[('IN', 'InProgress'), ('QF', 'QuickFinisher'), ('LL', 'LazyLoader'), ('SU', 'SilentUser')], max_length=25),
        ),
    ]
