# Generated by Django 3.2.18 on 2023-04-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20230328_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
