# Generated by Django 3.2.18 on 2023-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20230406_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge',
            field=models.CharField(choices=[('InProgress', 'InProgress'), ('QuickFinisher', 'QuickFinisher'), ('LazyLoader', 'LazyLoader'), ('SilentUser', 'SilentUser')], max_length=25),
        ),
    ]
