# Generated by Django 3.2.18 on 2023-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20230407_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer_Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_title', models.CharField(max_length=200)),
                ('submit_description', models.TextField()),
                ('code_snippets', models.TextField(blank=True, null=True)),
                ('submit_screenshots', models.ImageField(blank=True, null=True, upload_to='developer_task_screenshots/')),
                ('submit_file', models.FileField(blank=True, null=True, upload_to='developer_task_files/')),
                ('status', models.CharField(default='In progress', max_length=50)),
                ('submit_submit_date', models.DateTimeField(auto_now_add=True)),
                ('submit_developer_name', models.CharField(max_length=100)),
                ('submit_manager_name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('submit_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'developer_submit',
            },
        ),
    ]
