# Generated by Django 3.2.18 on 2023-04-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_developer_submit_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer_submit',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project_module'),
        ),
        migrations.AddField(
            model_name='developer_submit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
