# Generated by Django 3.2.18 on 2023-04-18 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0016_auto_20230417_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_module',
            name='user',
        ),
        migrations.AddField(
            model_name='project_module',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project_team',
            name='user',
        ),
        migrations.AddField(
            model_name='project_team',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
