# Generated by Django 3.2.18 on 2023-04-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20230418_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_task',
            name='task_util_minutes',
        ),
        migrations.AddField(
            model_name='project_task',
            name='timer_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
