# Generated by Django 3.2.18 on 2023-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20230419_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_module',
            name='module_completion_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project_module',
            name='module_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
