# Generated by Django 3.2.18 on 2023-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20230424_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_module',
            name='timer_duration',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
