# Generated by Django 3.2.18 on 2023-04-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_alter_project_module_timer_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_task',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project_module'),
        ),
        migrations.AlterField(
            model_name='project_task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
