# Generated by Django 3.2.18 on 2023-05-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20230424_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer_submit',
            name='submit_developer_email',
            field=models.URLField(blank=True, null=True),
        ),
    ]
