# Generated by Django 3.2.18 on 2023-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_developer_submit_submit_developer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer_submit',
            name='submit_developer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
