# Generated by Django 3.2.18 on 2023-04-09 18:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230321_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternate_contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='jobRole',
            field=models.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Product Manager', 'Product Manager'), ('Data Analyst', 'Data Analyst'), ('Data Scientist', 'Data Scientist'), ('User Experience (UX) Designer', 'User Experience (UX) Designer'), ('User Interface (UI) Designer', 'User Interface (UI) Designer'), ('Technical Program Manager', 'Technical Program Manager'), ('Technical Writer', 'Technical Writer'), ('DevOps Engineer', 'DevOps Engineer'), ('Network Engineer', 'Network Engineer'), ('Security Engineer', 'Security Engineer'), ('Cloud Solutions Architect', 'Cloud Solutions Architect'), ('Machine Learning Engineer', 'Machine Learning Engineer'), ('Artificial Intelligence (AI) Engineer', 'Artificial Intelligence (AI) Engineer'), ('Full Stack Developer', 'Full Stack Developer'), ('Front-End Developer', 'Front-End Developer'), ('Back-End Developer', 'Back-End Developer'), ('Mobile Application Developer', 'Mobile Application Developer'), ('Quality Assurance (QA) Engineer', 'Quality Assurance (QA) Engineer'), ('Game Developer', 'Game Developer'), ('Graphics Designer', 'Graphics Designer'), ('Technical Support Engineer', 'Technical Support Engineer'), ('Sales Manager', 'Sales Manager'), ('Marketing Manager', 'Marketing Manager'), ('Content Strategist', 'Content Strategist'), ('Business Analyst', 'Business Analyst'), ('Human Resources (HR) Manager', 'Human Resources (HR) Manager'), ('Financial Analyst', 'Financial Analyst'), ('Project Manager', 'Project Manager'), ('Supply Chain Manager', 'Supply Chain Manager'), ('Operations Manager', 'Operations Manager'), ('Executive Assistant', 'Executive Assistant'), ('Customer Success Manager', 'Customer Success Manager'), ('Solutions Engineer', 'Solutions Engineer'), ('System Administrator', 'System Administrator'), ('Database Administrator', 'Database Administrator'), ('Network Administrator', 'Network Administrator'), ('Web Designer', 'Web Designer'), ('Web Developer', 'Web Developer'), ('Information Security Analyst', 'Information Security Analyst'), ('Data Architect', 'Data Architect'), ('Solutions Architect', 'Solutions Architect'), ('Cloud Engineer', 'Cloud Engineer'), ('Video Producer', 'Video Producer'), ('Technical Recruiter', 'Technical Recruiter'), ('Creative Director', 'Creative Director'), ('Product Marketing Manager', 'Product Marketing Manager'), ('Email Marketing Manager', 'Email Marketing Manager'), ('Social Media Manager', 'Social Media Manager'), ('Business Development Manager', 'Business Development Manager'), ('Account Manager', 'Account Manager'), ('Public Relations (PR) Manager', 'Public Relations (PR) Manager'), ('Event Planner', 'Event Planner'), ('Brand Manager', 'Brand Manager'), ('Community Manager', 'Community Manager'), ('Training Manager', 'Training Manager'), ('Corporate Trainer', 'Corporate Trainer'), ('Talent Acquisition Manager', 'Talent Acquisition Manager'), ('Legal Counsel', 'Legal Counsel'), ('Intellectual Property (IP) Attorney', 'Intellectual Property (IP) Attorney'), ('Patent Attorney', 'Patent Attorney'), ('Environmental Health and Safety (EHS) Manager', 'Environmental Health and Safety (EHS) Manager'), ('Sustainability Manager', 'Sustainability Manager'), ('Facilities Manager', 'Facilities Manager'), ('Information Technology (IT) Manager', 'Information Technology (IT) Manager'), ('IT Project Manager', 'IT Project Manager'), ('IT Business Analyst', 'IT Business Analyst'), ('IT Security Analyst', 'IT Security Analyst'), ('IT Auditor', 'IT Auditor'), ('IT Consultant', 'IT Consultant')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Ahmedabad', 'Ahmedabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Pune', 'Pune'), ('Surat', 'Surat'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Kanpur', 'Kanpur'), ('Nagpur', 'Nagpur'), ('Visakhapatnam', 'Visakhapatnam'), ('Bhopal', 'Bhopal'), ('Patna', 'Patna'), ('Ludhiana', 'Ludhiana'), ('Agra', 'Agra'), ('Nashik', 'Nashik'), ('Vadodara', 'Vadodara'), ('Varanasi', 'Varanasi'), ('Srinagar', 'Srinagar'), ('Aurangabad', 'Aurangabad'), ('Dhanbad', 'Dhanbad'), ('Amritsar', 'Amritsar'), ('Navi Mumbai', 'Navi Mumbai'), ('Allahabad', 'Allahabad'), ('Ranchi', 'Ranchi'), ('Haora', 'Haora'), ('Coimbatore', 'Coimbatore'), ('Jabalpur', 'Jabalpur'), ('Gwalior', 'Gwalior'), ('Vijayawada', 'Vijayawada'), ('Jodhpur', 'Jodhpur'), ('Madurai', 'Madurai'), ('Raipur', 'Raipur'), ('Kota', 'Kota'), ('Guwahati', 'Guwahati'), ('Chandigarh', 'Chandigarh'), ('Solapur', 'Solapur'), ('Hubli and Dharwad', 'Hubli and Dharwad'), ('Bareilly', 'Bareilly'), ('Moradabad', 'Moradabad'), ('Mysore', 'Mysore'), ('Gurgaon', 'Gurgaon'), ('Aligarh', 'Aligarh'), ('Jalandhar', 'Jalandhar'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Bhubaneswar', 'Bhubaneswar'), ('Salem', 'Salem'), ('Mira and Bhayander', 'Mira and Bhayander'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur'), ('Gorakhpur', 'Gorakhpur'), ('Guntur', 'Guntur'), ('Bikaner', 'Bikaner'), ('Amravati', 'Amravati'), ('Noida', 'Noida'), ('Jamshedpur', 'Jamshedpur'), ('Bhilai Nagar', 'Bhilai Nagar'), ('Warangal', 'Warangal'), ('Cuttack', 'Cuttack'), ('Firozabad', 'Firozabad'), ('Kochi', 'Kochi'), ('Bhavnagar', 'Bhavnagar'), ('Dehradun', 'Dehradun')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100, null=True),
        ),
    ]
