# Generated by Django 3.2.18 on 2023-04-15 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_github_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_title', models.CharField(max_length=200)),
                ('scehdule_description', models.TextField()),
                ('schedule_meeting_url', models.URLField()),
                ('schedule_created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
