# Generated by Django 3.2.18 on 2023-04-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='scehdule_description',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_description',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_documents',
            field=models.FileField(default=False, upload_to='schedule_documents/'),
        ),
    ]
