# Generated by Django 3.2.18 on 2023-04-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20230415_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_documents',
            field=models.FileField(blank=True, null=True, upload_to='schedule_documents/'),
        ),
    ]
