# Generated by Django 3.2.18 on 2023-04-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20230415_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_meeting_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
