# Generated by Django 3.2.18 on 2023-04-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_schedule_schedule_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_meeting_date',
            field=models.DateTimeField(),
        ),
    ]
