# Generated by Django 3.2.18 on 2023-04-17 16:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230416_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
