# Generated by Django 3.2.18 on 2023-04-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_timer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='timer',
            table='timer',
        ),
    ]
